src/main/java/com/xuebusi/cms/base/modules/sys/entity/User.java
package com.xuebusi.cms.base.modules.sys.entity;

import com.xuebusi.cms.common.config.Global;
import com.xuebusi.cms.common.persistence.DataEntity;
import com.xuebusi.cms.common.utils.Collections3;
import com.xuebusi.cms.common.utils.excel.annotation.ExcelField;
import com.xuebusi.cms.common.utils.excel.fieldtype.RoleListType;
import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.google.common.collect.Lists;
import org.hibernate.validator.constraints.Email;
import org.hibernate.validator.constraints.Length;

import javax.validation.constraints.NotNull;
import java.util.Date;
import java.util.List;

/**
 * 用户Entity
 *
 * @author Idea
 * @version 2013-12-05
 */
public class User extends DataEntity<User> {

    private static final long serialVersionUID = 1L;
    private Office company;    // 归属公司
    private Office office;    // 归属部门
    private String loginName;// 登录名
    private String password;// 密码
    private String no;        // 工号
    private String name;    // 姓名
    private String email;    // 邮箱
    private String phone;    // 电话
    private String mobile;    // 手机
    private String userType;// 用户类型
    private String loginIp;    // 最后登陆IP
    private Date loginDate;    // 最后登陆日期
    private String loginFlag;    // 是否允许登陆
    private String photo;    // 头像

    private String oldLoginName;// 原登录名
    private String newPassword;    // 新密码

    private String oldLoginIp;    // 上次登陆IP
    private Date oldLoginDate;    // 上次登陆日期

    private Role role;    // 根据角色查询用户条件

    private List<Role> roleList = Lists.newArrayList(); // 拥有角色列表

    public User() {
        super();
        this.loginFlag = Global.YES;
    }

    public User(String id) {
        super(id);
    }

    public User(String id, String loginName) {
        super(id);
        this.loginName = loginName;
    }

    public User(Role role) {
        super();
        this.role = role;
    }

    public String getPhoto() {
        return photo;
    }

    public void setPhoto(String photo) {
        this.photo = photo;
    }

    public String getLoginFlag() {
        return loginFlag;
    }

    public void setLoginFlag(String loginFlag) {
        this.loginFlag = loginFlag;
    }

    @ExcelField(title = "ID", type = 1, align = 2, sort = 1)
    public String getId() {
        return id;
    }

    @JsonIgnore
    @NotNull(message = "归属公司不能为空")
    @ExcelField(title = "归属公司", align = 2, sort = 20)
    public Office getCompany() {
        return company;
    }

    public void setCompany(Office company) {
        this.company = company;
    }

    @JsonIgnore
    @NotNull(message = "归属部门不能为空")
    @ExcelField(title = "归属部门", align = 2, sort = 25)
    public Office getOffice() {
        return office;
    }

    public void setOffice(Office office) {
        this.office = office;
    }

    @Length(min = 1, max = 100, message = "登录名长度必须介于 1 和 100 之间")
    @ExcelField(title = "登录名", align = 2, sort = 30)
    public String getLoginName() {
        return loginName;
    }

    public void setLoginName(String loginName) {
        this.loginName = loginName;
    }

    @JsonIgnore
    @Length(min = 1, max = 100, message = "密码长度必须介于 1 和 100 之间")
    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    @Length(min = 1, max = 100, message = "姓名长度必须介于 1 和 100 之间")
    @ExcelField(title = "姓名", align = 2, sort = 40)
    public String getName() {
        return name;
    }

    @Length(min = 1, max = 100, message = "工号长度必须介于 1 和 100 之间")
    @ExcelField(title = "工号", align = 2, sort = 45)
    public String getNo() {
        return no;
    }

    public void setNo(String no) {
        this.no = no;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Email(message = "邮箱格式不正确")
    @Length(min = 0, max = 200, message = "邮箱长度必须介于 1 和 200 之间")
    @ExcelField(title = "邮箱", align = 1, sort = 50)
    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    @Length(min = 0, max = 200, message = "电话长度必须介于 1 和 200 之间")
    @ExcelField(title = "电话", align = 2, sort = 60)
    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    @Length(min = 0, max = 200, message = "手机长度必须介于 1 和 200 之间")
    @ExcelField(title = "手机", align = 2, sort = 70)
    public String getMobile() {
        return mobile;
    }

    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    @ExcelField(title = "备注", align = 1, sort = 900)
    public String getRemarks() {
        return remarks;
    }

    @Length(min = 0, max = 100, message = "用户类型长度必须介于 1 和 100 之间")
    @ExcelField(title = "用户类型", align = 2, sort = 80, dictType = "sys_user_type")
    public String getUserType() {
        return userType;
    }

    public void setUserType(String userType) {
        this.userType = userType;
    }

    @ExcelField(title = "创建时间", type = 0, align = 1, sort = 90)
    public Date getCreateDate() {
        return createDate;
    }

    @ExcelField(title = "最后登录IP", type = 1, align = 1, sort = 100)
    public String getLoginIp() {
        return loginIp;
    }

    public void setLoginIp(String loginIp) {
        this.loginIp = loginIp;
    }

    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    @ExcelField(title = "最后登录日期", type = 1, align = 1, sort = 110)
    public Date getLoginDate() {
        return loginDate;
    }

    public void setLoginDate(Date loginDate) {
        this.loginDate = loginDate;
    }

    public String getOldLoginName() {
        return oldLoginName;
    }

    public void setOldLoginName(String oldLoginName) {
        this.oldLoginName = oldLoginName;
    }

    public String getNewPassword() {
        return newPassword;
    }

    public void setNewPassword(String newPassword) {
        this.newPassword = newPassword;
    }

    public String getOldLoginIp() {
        if (oldLoginIp == null) {
            return loginIp;
        }
        return oldLoginIp;
    }

    public void setOldLoginIp(String oldLoginIp) {
        this.oldLoginIp = oldLoginIp;
    }

    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    public Date getOldLoginDate() {
        if (oldLoginDate == null) {
            return loginDate;
        }
        return oldLoginDate;
    }

    public void setOldLoginDate(Date oldLoginDate) {
        this.oldLoginDate = oldLoginDate;
    }

    public Role getRole() {
        return role;
    }

    public void setRole(Role role) {
        this.role = role;
    }

    @JsonIgnore
    @ExcelField(title = "拥有角色", align = 1, sort = 800, fieldType = RoleListType.class)
    public List<Role> getRoleList() {
        return roleList;
    }

    public void setRoleList(List<Role> roleList) {
        this.roleList = roleList;
    }

    @JsonIgnore
    public List<String> getRoleIdList() {
        List<String> roleIdList = Lists.newArrayList();
        for (Role role : roleList) {
            roleIdList.add(role.getId());
        }
        return roleIdList;
    }

    public void setRoleIdList(List<String> roleIdList) {
        roleList = Lists.newArrayList();
        for (String roleId : roleIdList) {
            Role role = new Role();
            role.setId(roleId);
            roleList.add(role);
        }
    }

    /**
     * 用户拥有的角色名称字符串, 多个角色名称用','分隔.
     */
    public String getRoleNames() {
        return Collections3.extractToString(roleList, "name", ",");
    }

    public boolean isAdmin() {
        return isAdmin(this.id);
    }

    public static boolean isAdmin(String id) {
        return id != null && "1".equals(id);
    }

    @Override
    public String toString() {
        return id;
    }
}

src/main/java/com/xuebusi/cms/base/modules/redis/web/RedisClusterController.java
package com.xuebusi.cms.base.modules.redis.web;

import com.xuebusi.cms.base.modules.redis.entity.RedisCluster;
import com.xuebusi.cms.base.modules.redis.service.RedisClusterService;
import com.xuebusi.cms.common.config.Global;
import com.xuebusi.cms.common.persistence.Page;
import com.xuebusi.cms.common.web.BaseController;
import org.apache.commons.lang3.StringUtils;
import org.apache.shiro.authz.annotation.RequiresPermissions;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.servlet.mvc.support.RedirectAttributes;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

/**
 * 集群配置Controller
 *
 * @author shiyanjun
 * @version 2018-11-14
 */
@Controller
@RequestMapping(value = "${adminPath}/redis/redisCluster")
public class RedisClusterController extends BaseController {

    @Autowired
    private RedisClusterService redisClusterService;

    @ModelAttribute
    public RedisCluster get(@RequestParam(required = false) String id) {
        RedisCluster entity = null;
        if (StringUtils.isNotBlank(id)) {
            entity = redisClusterService.get(id);
        }
        if (entity == null) {
            entity = new RedisCluster();
        }
        return entity;
    }

    @RequiresPermissions("redis:redisCluster:view")
    @RequestMapping(value = {"list", ""})
    public String list(RedisCluster redisCluster, HttpServletRequest request, HttpServletResponse response, Model model) {
        Page<RedisCluster> page = redisClusterService.findPage(new Page<RedisCluster>(request, response), redisCluster);
        model.addAttribute("page", page);
        return "base/modules/redis/redisClusterList";
    }

    @RequiresPermissions("redis:redisCluster:view")
    @RequestMapping(value = "form")
    public String form(RedisCluster redisCluster, Model model) {
        model.addAttribute("redisCluster", redisCluster);
        return "base/modules/redis/redisClusterForm";
    }

    @RequiresPermissions("redis:redisCluster:edit")
    @RequestMapping(value = "save")
    public String save(RedisCluster redisCluster, Model model, RedirectAttributes redirectAttributes) {
        if (!beanValidator(model, redisCluster)) {
            return form(redisCluster, model);
        }
        redisClusterService.save(redisCluster);
        addMessage(redirectAttributes, "保存集群配置成功");
        return "redirect:" + Global.getAdminPath() + "/redis/redisCluster/?repage";
    }

    @RequiresPermissions("redis:redisCluster:edit")
    @RequestMapping(value = "delete")
    public String delete(RedisCluster redisCluster, RedirectAttributes redirectAttributes) {
        redisClusterService.delete(redisCluster);
        addMessage(redirectAttributes, "删除集群配置成功");
        return "redirect:" + Global.getAdminPath() + "/redis/redisCluster/?repage";
    }

}

src/main/java/com/xuebusi/cms/base/modules/redis/web/SysRedisController.java
package com.xuebusi.cms.base.modules.redis.web;

import com.xuebusi.cms.base.modules.redis.entity.SysRedis;
import com.xuebusi.cms.base.modules.redis.service.RedisService;
import com.xuebusi.cms.common.config.Global;
import com.xuebusi.cms.common.persistence.Page;
import com.xuebusi.cms.common.utils.StringUtils;
import com.xuebusi.cms.common.web.BaseController;
import org.apache.shiro.authz.annotation.RequiresPermissions;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.servlet.mvc.support.RedirectAttributes;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.util.HashMap;
import java.util.Map;

/**
 * 缓存管理Controller
 *
 * @author shiyanjun
 * @version 2018-10-20
 */
@Controller
@RequestMapping(value = "${adminPath}/redis/sysRedis")
public class SysRedisController extends BaseController {

    @Autowired
    private RedisService redisService;

    @ModelAttribute
    public SysRedis get(@RequestParam(required = false) SysRedis sysRedis) {
        if (sysRedis == null) {
            sysRedis = new SysRedis();
        } else {
            sysRedis = redisService.get(sysRedis.getRedisKey());
        }
        return sysRedis;
    }

    @RequiresPermissions("redis:sysRedis:view")
    @RequestMapping(value = {"list", ""})
    public String list(SysRedis sysRedis, HttpServletRequest request, HttpServletResponse response, Model model) {
        Page<SysRedis> page = redisService.findPage(new Page<>(request, response), sysRedis);
        model.addAttribute("page", page);
        return "base/modules/redis/sysRedisList";
    }

    @RequiresPermissions("redis:sysRedis:view")
    @RequestMapping(value = "form")
    public String form(SysRedis sysRedis, Model model) {
        SysRedis entity = null;
        if (StringUtils.isNotBlank(sysRedis.getRedisKey())) {
            entity = redisService.get(sysRedis.getRedisKey());
        }
        if (entity == null) {
            model.addAttribute("sysRedis", sysRedis);
        } else {
            model.addAttribute("sysRedis", entity);
        }
        return "base/modules/redis/sysRedisForm";
    }

    @RequiresPermissions("redis:sysRedis:edit")
    @RequestMapping(value = "save")
    public String save(SysRedis sysRedis, Model model, RedirectAttributes redirectAttributes) {
        if (!beanValidator(model, sysRedis)) {
            return form(sysRedis, model);
        }
        redisService.save(sysRedis);
        addMessage(redirectAttributes, "缓存保存成功");
        return "redirect:" + Global.getAdminPath() + "/redis/sysRedis/list?repage";
    }

    @RequiresPermissions("redis:sysRedis:edit")
    @RequestMapping(value = "delete")
    public String delete(SysRedis sysRedis, RedirectAttributes redirectAttributes) {
        redisService.del(sysRedis);
        addMessage(redirectAttributes, "缓存删除成功");
        return "redirect:" + Global.getAdminPath() + "/redis/sysRedis/list?repage";
    }

    @RequiresPermissions("redis:sysRedis:edit")
    @RequestMapping(value = "remove")
    public String remove(SysRedis sysRedis, RedirectAttributes redirectAttributes) {
        redisService.remove(sysRedis);
        redirectAttributes.addAttribute("redisKey", sysRedis.getRedisKey());
        addMessage(redirectAttributes, "元素删除成功");
        return "redirect:" + Global.getAdminPath() + "/redis/sysRedis/form?repage";
    }

    @RequiresPermissions("redis:sysRedis:edit")
    @RequestMapping(value = "rename")
    public String rename(SysRedis sysRedis, RedirectAttributes redirectAttributes) {
        if (!sysRedis.getOldRedisKey().equals(sysRedis.getRedisKey())) {
            redisService.rename(sysRedis);
        }
        redirectAttributes.addAttribute("redisKey", sysRedis.getRedisKey());
        addMessage(redirectAttributes, "名称更新成功");
        return "redirect:" + Global.getAdminPath() + "/redis/sysRedis/form?repage";
    }

    @RequiresPermissions("redis:sysRedis:edit")
    @RequestMapping(value = "updateExpire")
    public String updateExpire(SysRedis sysRedis, RedirectAttributes redirectAttributes) {
        redisService.updateExpire(sysRedis);
        redirectAttributes.addAttribute("redisKey", sysRedis.getRedisKey());
        addMessage(redirectAttributes, "过期时间更新成功");
        return "redirect:" + Global.getAdminPath() + "/redis/sysRedis/form?repage";
    }

    @RequiresPermissions("redis:sysRedis:edit")
    @RequestMapping(value = "addValue")
    @ResponseBody
    public Map<String, Object> addValue(SysRedis sysRedis, RedirectAttributes redirectAttributes) {
        redisService.addValue(sysRedis);
        Map<String, Object> map = new HashMap<>();
        map.put("redisKey", sysRedis.getRedisKey());
        map.put("message", "元素更新成功");
        map.put("redirectUrl", "/redis/sysRedis/form");
        return map;
    }
}

src/main/java/com/xuebusi/cms/base/modules/sys/web/LogController.java
package com.xuebusi.cms.base.modules.sys.web;

import com.xuebusi.cms.base.modules.sys.entity.Log;
import com.xuebusi.cms.base.modules.sys.service.LogService;
import com.xuebusi.cms.common.persistence.Page;
import com.xuebusi.cms.common.web.BaseController;
import org.apache.shiro.authz.annotation.RequiresPermissions;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

/**
 * 日志Controller
 *
 * @author Idea
 * @version 2013-6-2
 */
@Controller
@RequestMapping(value = "${adminPath}/sys/log")
public class LogController extends BaseController {

    @Autowired
    private LogService logService;

    @RequiresPermissions("sys:log:view")
    @RequestMapping(value = {"list", ""})
    public String list(Log log, HttpServletRequest request, HttpServletResponse response, Model model) {
        Page<Log> page = logService.findPage(new Page<Log>(request, response), log);
        model.addAttribute("page", page);
        return "base/modules/sys/logList";
    }

}

src/main/webapp/WEB-INF/views/base/modules/sys/areaList.jsp
<!DOCTYPE html>
<%@ page contentType="text/html;charset=UTF-8" %>
<%@ include file="/WEB-INF/views/include/taglib.jsp" %>
<html>
<head>
    <%@ include file="/WEB-INF/views/include/head.jsp" %>
    <title>区域管理</title>
    <meta name="decorator" content="default"/>
    <%@include file="/WEB-INF/views/include/treetable.jsp" %>
    <script type="text/javascript">
        $(document).ready(function () {
            var tpl = $("#treeTableTpl").html().replace(/(\/\/\<!\-\-)|(\/\/\-\->)/g, "");
            var data = ${fns:toJson(list)}, rootId = "0";
            addRow("#treeTableList", tpl, data, rootId, true);
            $("#treeTable").treeTable({expandLevel: 5});
        });
        function addRow(list, tpl, data, pid, root) {
            for (var i = 0; i < data.length; i++) {
                var row = data[i];
                if ((${fns:jsGetVal('row.parentId')}) == pid) {
                    $(list).append(Mustache.render(tpl, {
                        dict: {
                            type: getDictLabel(${fns:toJson(fns:getDictList('sys_area_type'))}, row.type)
                        }, pid: (root ? 0 : pid), row: row
                    }));
                    addRow(list, tpl, data, row.id);
                }
            }
        }
    </script>
</head>
<body>
<ul class="nav nav-tabs">
    <li class="active"><a href="${ctx}/sys/area/">区域列表</a></li>
    <shiro:hasPermission name="sys:area:edit">
        <li><a href="${ctx}/sys/area/form">区域添加</a></li>
    </shiro:hasPermission>
</ul>
<sys:message content="${message}"/>
<table id="treeTable" class="table table-striped table-bordered table-condensed">
    <thead>
    <tr>
        <th>区域名称</th>
        <th>区域编码</th>
        <th>区域类型</th>
        <th>备注</th>
        <shiro:hasPermission name="sys:area:edit">
            <th>操作</th>
        </shiro:hasPermission></tr>
    </thead>
    <tbody id="treeTableList"></tbody>
</table>
<script type="text/template" id="treeTableTpl">
    <tr id="{{row.id}}" pId="{{pid}}">
        <td><a href="${ctx}/sys/area/form?id={{row.id}}">{{row.name}}</a></td>
        <td>{{row.code}}</td>
        <td>{{dict.type}}</td>
        <td>{{row.remarks}}</td>
        <shiro:hasPermission name="sys:area:edit">
            <td>
                <a href="${ctx}/sys/area/form?id={{row.id}}">修改</a>
                <a href="${ctx}/sys/area/delete?id={{row.id}}" onclick="return confirmx('要删除该区域及所有子区域项吗？', this.href)">删除</a>
                <a href="${ctx}/sys/area/form?parent.id={{row.id}}">添加下级区域</a>
            </td>
        </shiro:hasPermission>
    </tr>
</script>
</body>
</html>

src/main/webapp/WEB-INF/views/base/modules/sys/dictForm.jsp
<!DOCTYPE html>
<%@ page contentType="text/html;charset=UTF-8" %>
<%@ include file="/WEB-INF/views/include/taglib.jsp" %>
<html>
<head>
    <%@ include file="/WEB-INF/views/include/head.jsp" %>
    <title>字典管理</title>
    <meta name="decorator" content="default"/>
    <script type="text/javascript">
        $(document).ready(function () {
            $("#value").focus();
            $("#inputForm").validate({
                submitHandler: function (form) {
                    loading('正在提交，请稍等...');
                    form.submit();
                },
                errorContainer: "#messageBox",
                errorPlacement: function (error, element) {
                    $("#messageBox").text("输入有误，请先更正。");
                    if (element.is(":checkbox") || element.is(":radio") || element.parent().is(".input-append")) {
                        error.appendTo(element.parent().parent());
                    } else {
                        error.insertAfter(element);
                    }
                }
            });
        });
    </script>
</head>
<body>
<ul class="nav nav-tabs">
    <li><a href="${ctx}/sys/dict/">字典列表</a></li>
    <li class="active"><a href="${ctx}/sys/dict/form?id=${dict.id}">字典<shiro:hasPermission
            name="sys:dict:edit">${not empty dict.id?'修改':'添加'}</shiro:hasPermission><shiro:lacksPermission
            name="sys:dict:edit">查看</shiro:lacksPermission></a></li>
</ul>
<br/>
<form:form id="inputForm" modelAttribute="dict" action="${ctx}/sys/dict/save" method="post" class="form-horizontal">
    <form:hidden path="id"/>
    <sys:message content="${message}"/>
    <div class="control-group">
        <label class="control-label">键值:</label>
        <div class="controls">
            <form:input path="value" htmlEscape="false" maxlength="50" class="required"/>
        </div>
    </div>
    <div class="control-group">
        <label class="control-label">标签:</label>
        <div class="controls">
            <form:input path="label" htmlEscape="false" maxlength="50" class="required"/>
        </div>
    </div>
    <div class="control-group">
        <label class="control-label">类型:</label>
        <div class="controls">
            <form:input path="type" htmlEscape="false" maxlength="50" class="required abc"/>
        </div>
    </div>
    <div class="control-group">
        <label class="control-label">描述:</label>
        <div class="controls">
            <form:input path="description" htmlEscape="false" maxlength="50" class="required"/>
        </div>
    </div>
    <div class="control-group">
        <label class="control-label">排序:</label>
        <div class="controls">
            <form:input path="sort" htmlEscape="false" maxlength="11" class="required digits"/>
        </div>
    </div>
    <div class="control-group">
        <label class="control-label">备注:</label>
        <div class="controls">
            <form:textarea path="remarks" htmlEscape="false" rows="3" maxlength="200" class="input-xlarge"/>
        </div>
    </div>
    <div class="form-actions">
        <shiro:hasPermission name="sys:dict:edit"><input id="btnSubmit" class="btn btn-primary" type="submit"
                                                         value="保 存"/>&nbsp;</shiro:hasPermission>
        <input id="btnCancel" class="btn" type="button" value="返 回" onclick="history.go(-1)"/>
    </div>
</form:form>
</body>
</html>

src/main/webapp/WEB-INF/views/base/modules/sys/roleList.jsp
<!DOCTYPE html>
<%@ page contentType="text/html;charset=UTF-8" %>
<%@ include file="/WEB-INF/views/include/taglib.jsp" %>
<html>
<head>
    <%@ include file="/WEB-INF/views/include/head.jsp" %>
    <title>角色管理</title>
    <meta name="decorator" content="default"/>
</head>
<body>
<ul class="nav nav-tabs">
    <li class="active"><a href="${ctx}/sys/role/">角色列表</a></li>
    <shiro:hasPermission name="sys:role:edit">
        <li><a href="${ctx}/sys/role/form">角色添加</a></li>
    </shiro:hasPermission>
</ul>
<sys:message content="${message}"/>
<table id="contentTable" class="table table-striped table-bordered table-condensed">
    <tr>
        <th>角色名称</th>
        <th>英文名称</th>
        <th>归属机构</th>
        <th>数据范围</th>
        <shiro:hasPermission name="sys:role:edit">
            <th>操作</th>
        </shiro:hasPermission></tr>
    <c:forEach items="${list}" var="role">
        <tr>
            <td><a href="form?id=${role.id}">${role.name}</a></td>
            <td><a href="form?id=${role.id}">${role.enname}</a></td>
            <td>${role.office.name}</td>
            <td>${fns:getDictLabel(role.dataScope, 'sys_data_scope', '无')}</td>
            <shiro:hasPermission name="sys:role:edit">
                <td>
                    <a href="${ctx}/sys/role/assign?id=${role.id}">分配</a>
                    <c:if test="${(role.sysData eq fns:getDictValue('是', 'yes_no', '1') && fns:getUser().admin)||!(role.sysData eq fns:getDictValue('是', 'yes_no', '1'))}">
                        <a href="${ctx}/sys/role/form?id=${role.id}">修改</a>
                    </c:if>
                    <a href="${ctx}/sys/role/delete?id=${role.id}"
                       onclick="return confirmx('确认要删除该角色吗？', this.href)">删除</a>
                </td>
            </shiro:hasPermission>
        </tr>
    </c:forEach>
</table>
</body>
</html>